version: '3.8'
name: banner-service
services:
  server:
    build: .
    environment:
      HTTP_PORT: 3000
      DB_URL: postgresql://postgres:postgres@db:5432/banner?sslmode=disable
      REDIS_URL: redis://redis:6379/0?protocol=3
    ports:
      - "4000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    build:
      dockerfile: db.Dockerfile
    environment:
      POSTGRES_DB: banner
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "4001:5432"
    healthcheck:
      test: pg_isready
      interval: 1s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.2-alpine
    ports:
      - "4002:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 1s
      timeout: 5s
      retries: 10
